### ISSUE TITLE
[BUG] failed to add mnemonic

### ISSUE THREAD

**Issue by a1is3n** [felixbrucker/hddcoin-blockchain#10]
desc: 
     failed to add mnemonic keys after new update.  (1.2.9-og-pooling-1.0.2)
error :
     "'******' is not in the mnemonic dictionary; may be misspelled"

steps:
   git clone https://github.com/felixbrucker/hddcoin-blockchain.git
   cd hddcoin-blockchain
   sh install.sh
   . ./activate
   hddcoin init
   hddcoin keys add

OS: ubuntu 20.04

there is no error at 1.2.6.2-og-pooling-1.0.2.

**Comment by felixbrucker** [comment]
Does this only happen on the OG patched version, or also on the official 1.2.9 release?

**Comment by a1is3n** [comment]
same error at your  release 1.2.9.
same error at official hddcoin release 1.2.9
no error at official chia release 1.2.9
os: ubuntu 20.04
os: windows 10 21h1

PS C:\Users\testQ\AppData\Local\hddcoin-blockchain\app-1.2.9\resources\app.asar.unpacked\daemon> .\hddcoin.exe keys add
Enter the mnemonic you want to use: *** *** *** ***
'exchange' is not in the mnemonic dictionary; may be misspelled.

problem is 'exchange' is the one of the mnemonic keys.

same on gui

![resim](https://user-images.githubusercontent.com/8135588/136210918-20bf5f92-1265-4f2a-ae40-0707b48afec2.png)

**Comment by felixbrucker** [comment]
Thanks, i will let the devs know 👍

**Comment by felixbrucker** [comment]
Fixed in this fork with https://github.com/felixbrucker/hddcoin-blockchain/commit/29637236152f6230c11d86f9244fd37197110f6d
Updated release will be built as well

Upstream will have to fix as well
